/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.1 Nightly Build 2586
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* CapSense_Cmod */
#define CapSense_Cmod_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Cmod_0_INBUF_ENABLED 0u
#define CapSense_Cmod_0_INIT_DRIVESTATE 1u
#define CapSense_Cmod_0_INIT_MUXSEL 0u
#define CapSense_Cmod_0_INPUT_SYNC 2u
#define CapSense_Cmod_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Cmod_0_NUM 7u
#define CapSense_Cmod_0_PORT GPIO_PRT7
#define CapSense_Cmod_0_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Cmod_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Cmod_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Cmod_INBUF_ENABLED 0u
#define CapSense_Cmod_INIT_DRIVESTATE 1u
#define CapSense_Cmod_INIT_MUXSEL 0u
#define CapSense_Cmod_INPUT_SYNC 2u
#define CapSense_Cmod_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Cmod_NUM 7u
#define CapSense_Cmod_PORT GPIO_PRT7
#define CapSense_Cmod_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Cmod_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* CapSense_Csh */
#define CapSense_Csh_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Csh_0_INBUF_ENABLED 0u
#define CapSense_Csh_0_INIT_DRIVESTATE 1u
#define CapSense_Csh_0_INIT_MUXSEL 0u
#define CapSense_Csh_0_INPUT_SYNC 2u
#define CapSense_Csh_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Csh_0_NUM 2u
#define CapSense_Csh_0_PORT GPIO_PRT7
#define CapSense_Csh_0_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Csh_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Csh_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Csh_INBUF_ENABLED 0u
#define CapSense_Csh_INIT_DRIVESTATE 1u
#define CapSense_Csh_INIT_MUXSEL 0u
#define CapSense_Csh_INPUT_SYNC 2u
#define CapSense_Csh_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Csh_NUM 2u
#define CapSense_Csh_PORT GPIO_PRT7
#define CapSense_Csh_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Csh_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* CapSense_Shield */
#define CapSense_Shield_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Shield_0_INBUF_ENABLED 0u
#define CapSense_Shield_0_INIT_DRIVESTATE 1u
#define CapSense_Shield_0_INIT_MUXSEL 0u
#define CapSense_Shield_0_INPUT_SYNC 2u
#define CapSense_Shield_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Shield_0_NUM 0u
#define CapSense_Shield_0_PORT GPIO_PRT1
#define CapSense_Shield_0_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Shield_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Shield_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Shield_INBUF_ENABLED 0u
#define CapSense_Shield_INIT_DRIVESTATE 1u
#define CapSense_Shield_INIT_MUXSEL 0u
#define CapSense_Shield_INPUT_SYNC 2u
#define CapSense_Shield_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Shield_NUM 0u
#define CapSense_Shield_PORT GPIO_PRT1
#define CapSense_Shield_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Shield_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* CapSense_Rx */
#define CapSense_Rx_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Rx_0_INBUF_ENABLED 0u
#define CapSense_Rx_0_INIT_DRIVESTATE 1u
#define CapSense_Rx_0_INIT_MUXSEL 4u
#define CapSense_Rx_0_INPUT_SYNC 2u
#define CapSense_Rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Rx_0_NUM 1u
#define CapSense_Rx_0_PORT GPIO_PRT8
#define CapSense_Rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Rx_1_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Rx_1_INBUF_ENABLED 0u
#define CapSense_Rx_1_INIT_DRIVESTATE 1u
#define CapSense_Rx_1_INIT_MUXSEL 4u
#define CapSense_Rx_1_INPUT_SYNC 2u
#define CapSense_Rx_1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Rx_1_NUM 2u
#define CapSense_Rx_1_PORT GPIO_PRT8
#define CapSense_Rx_1_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Rx_1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* CapSense_Tx */
#define CapSense_Tx_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Tx_0_INBUF_ENABLED 0u
#define CapSense_Tx_0_INIT_DRIVESTATE 1u
#define CapSense_Tx_0_INIT_MUXSEL 0u
#define CapSense_Tx_0_INPUT_SYNC 2u
#define CapSense_Tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Tx_0_NUM 0u
#define CapSense_Tx_0_PORT GPIO_PRT1
#define CapSense_Tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Tx_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Tx_INBUF_ENABLED 0u
#define CapSense_Tx_INIT_DRIVESTATE 1u
#define CapSense_Tx_INIT_MUXSEL 0u
#define CapSense_Tx_INPUT_SYNC 2u
#define CapSense_Tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Tx_NUM 0u
#define CapSense_Tx_PORT GPIO_PRT1
#define CapSense_Tx_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* CapSense_Sns */
#define CapSense_Sns_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Sns_0_INBUF_ENABLED 0u
#define CapSense_Sns_0_INIT_DRIVESTATE 1u
#define CapSense_Sns_0_INIT_MUXSEL 0u
#define CapSense_Sns_0_INPUT_SYNC 2u
#define CapSense_Sns_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Sns_0_NUM 3u
#define CapSense_Sns_0_PORT GPIO_PRT8
#define CapSense_Sns_0_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Sns_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Sns_1_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Sns_1_INBUF_ENABLED 0u
#define CapSense_Sns_1_INIT_DRIVESTATE 1u
#define CapSense_Sns_1_INIT_MUXSEL 0u
#define CapSense_Sns_1_INPUT_SYNC 2u
#define CapSense_Sns_1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Sns_1_NUM 4u
#define CapSense_Sns_1_PORT GPIO_PRT8
#define CapSense_Sns_1_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Sns_1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Sns_2_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Sns_2_INBUF_ENABLED 0u
#define CapSense_Sns_2_INIT_DRIVESTATE 1u
#define CapSense_Sns_2_INIT_MUXSEL 0u
#define CapSense_Sns_2_INPUT_SYNC 2u
#define CapSense_Sns_2_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Sns_2_NUM 5u
#define CapSense_Sns_2_PORT GPIO_PRT8
#define CapSense_Sns_2_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Sns_2_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Sns_3_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Sns_3_INBUF_ENABLED 0u
#define CapSense_Sns_3_INIT_DRIVESTATE 1u
#define CapSense_Sns_3_INIT_MUXSEL 0u
#define CapSense_Sns_3_INPUT_SYNC 2u
#define CapSense_Sns_3_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Sns_3_NUM 6u
#define CapSense_Sns_3_PORT GPIO_PRT8
#define CapSense_Sns_3_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Sns_3_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_Sns_4_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_Sns_4_INBUF_ENABLED 0u
#define CapSense_Sns_4_INIT_DRIVESTATE 1u
#define CapSense_Sns_4_INIT_MUXSEL 0u
#define CapSense_Sns_4_INPUT_SYNC 2u
#define CapSense_Sns_4_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_Sns_4_NUM 7u
#define CapSense_Sns_4_PORT GPIO_PRT8
#define CapSense_Sns_4_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_Sns_4_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* CapSense_CintA */
#define CapSense_CintA_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_CintA_0_INBUF_ENABLED 0u
#define CapSense_CintA_0_INIT_DRIVESTATE 1u
#define CapSense_CintA_0_INIT_MUXSEL 0u
#define CapSense_CintA_0_INPUT_SYNC 2u
#define CapSense_CintA_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_CintA_0_NUM 1u
#define CapSense_CintA_0_PORT GPIO_PRT7
#define CapSense_CintA_0_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_CintA_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_CintA_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_CintA_INBUF_ENABLED 0u
#define CapSense_CintA_INIT_DRIVESTATE 1u
#define CapSense_CintA_INIT_MUXSEL 0u
#define CapSense_CintA_INPUT_SYNC 2u
#define CapSense_CintA_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_CintA_NUM 1u
#define CapSense_CintA_PORT GPIO_PRT7
#define CapSense_CintA_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_CintA_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* CapSense_CintB */
#define CapSense_CintB_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_CintB_0_INBUF_ENABLED 0u
#define CapSense_CintB_0_INIT_DRIVESTATE 1u
#define CapSense_CintB_0_INIT_MUXSEL 0u
#define CapSense_CintB_0_INPUT_SYNC 2u
#define CapSense_CintB_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_CintB_0_NUM 2u
#define CapSense_CintB_0_PORT GPIO_PRT7
#define CapSense_CintB_0_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_CintB_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define CapSense_CintB_DRIVEMODE CY_GPIO_DM_ANALOG
#define CapSense_CintB_INBUF_ENABLED 0u
#define CapSense_CintB_INIT_DRIVESTATE 1u
#define CapSense_CintB_INIT_MUXSEL 0u
#define CapSense_CintB_INPUT_SYNC 2u
#define CapSense_CintB_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define CapSense_CintB_NUM 2u
#define CapSense_CintB_PORT GPIO_PRT7
#define CapSense_CintB_SLEWRATE CY_GPIO_SLEW_FAST
#define CapSense_CintB_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* EnableWifi */
#define EnableWifi_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define EnableWifi_0_INBUF_ENABLED 0u
#define EnableWifi_0_INIT_DRIVESTATE 0u
#define EnableWifi_0_INIT_MUXSEL 0u
#define EnableWifi_0_INPUT_SYNC 2u
#define EnableWifi_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define EnableWifi_0_NUM 6u
#define EnableWifi_0_PORT GPIO_PRT2
#define EnableWifi_0_SLEWRATE CY_GPIO_SLEW_FAST
#define EnableWifi_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define EnableWifi_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define EnableWifi_INBUF_ENABLED 0u
#define EnableWifi_INIT_DRIVESTATE 0u
#define EnableWifi_INIT_MUXSEL 0u
#define EnableWifi_INPUT_SYNC 2u
#define EnableWifi_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define EnableWifi_NUM 6u
#define EnableWifi_PORT GPIO_PRT2
#define EnableWifi_SLEWRATE CY_GPIO_SLEW_FAST
#define EnableWifi_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* SDIO_HOST_CMD */
#define SDIO_HOST_CMD_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define SDIO_HOST_CMD_0_INBUF_ENABLED 1u
#define SDIO_HOST_CMD_0_INIT_DRIVESTATE 1u
#define SDIO_HOST_CMD_0_INIT_MUXSEL 2u
#define SDIO_HOST_CMD_0_INPUT_SYNC 2u
#define SDIO_HOST_CMD_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define SDIO_HOST_CMD_0_NUM 4u
#define SDIO_HOST_CMD_0_PORT GPIO_PRT2
#define SDIO_HOST_CMD_0_SLEWRATE CY_GPIO_SLEW_FAST
#define SDIO_HOST_CMD_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define SDIO_HOST_CMD_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define SDIO_HOST_CMD_INBUF_ENABLED 1u
#define SDIO_HOST_CMD_INIT_DRIVESTATE 1u
#define SDIO_HOST_CMD_INIT_MUXSEL 2u
#define SDIO_HOST_CMD_INPUT_SYNC 2u
#define SDIO_HOST_CMD_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define SDIO_HOST_CMD_NUM 4u
#define SDIO_HOST_CMD_PORT GPIO_PRT2
#define SDIO_HOST_CMD_SLEWRATE CY_GPIO_SLEW_FAST
#define SDIO_HOST_CMD_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* SDIO_HOST_DAT */
#define SDIO_HOST_DAT_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define SDIO_HOST_DAT_0_INBUF_ENABLED 1u
#define SDIO_HOST_DAT_0_INIT_DRIVESTATE 1u
#define SDIO_HOST_DAT_0_INIT_MUXSEL 2u
#define SDIO_HOST_DAT_0_INPUT_SYNC 2u
#define SDIO_HOST_DAT_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define SDIO_HOST_DAT_0_NUM 0u
#define SDIO_HOST_DAT_0_PORT GPIO_PRT2
#define SDIO_HOST_DAT_0_SLEWRATE CY_GPIO_SLEW_FAST
#define SDIO_HOST_DAT_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define SDIO_HOST_DAT_1_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define SDIO_HOST_DAT_1_INBUF_ENABLED 1u
#define SDIO_HOST_DAT_1_INIT_DRIVESTATE 1u
#define SDIO_HOST_DAT_1_INIT_MUXSEL 2u
#define SDIO_HOST_DAT_1_INPUT_SYNC 2u
#define SDIO_HOST_DAT_1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define SDIO_HOST_DAT_1_NUM 1u
#define SDIO_HOST_DAT_1_PORT GPIO_PRT2
#define SDIO_HOST_DAT_1_SLEWRATE CY_GPIO_SLEW_FAST
#define SDIO_HOST_DAT_1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define SDIO_HOST_DAT_2_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define SDIO_HOST_DAT_2_INBUF_ENABLED 1u
#define SDIO_HOST_DAT_2_INIT_DRIVESTATE 1u
#define SDIO_HOST_DAT_2_INIT_MUXSEL 2u
#define SDIO_HOST_DAT_2_INPUT_SYNC 2u
#define SDIO_HOST_DAT_2_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define SDIO_HOST_DAT_2_NUM 2u
#define SDIO_HOST_DAT_2_PORT GPIO_PRT2
#define SDIO_HOST_DAT_2_SLEWRATE CY_GPIO_SLEW_FAST
#define SDIO_HOST_DAT_2_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define SDIO_HOST_DAT_3_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define SDIO_HOST_DAT_3_INBUF_ENABLED 1u
#define SDIO_HOST_DAT_3_INIT_DRIVESTATE 1u
#define SDIO_HOST_DAT_3_INIT_MUXSEL 2u
#define SDIO_HOST_DAT_3_INPUT_SYNC 2u
#define SDIO_HOST_DAT_3_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define SDIO_HOST_DAT_3_NUM 3u
#define SDIO_HOST_DAT_3_PORT GPIO_PRT2
#define SDIO_HOST_DAT_3_SLEWRATE CY_GPIO_SLEW_FAST
#define SDIO_HOST_DAT_3_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* SDIO_HOST_sdClk */
#define SDIO_HOST_sdClk_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define SDIO_HOST_sdClk_0_INBUF_ENABLED 0u
#define SDIO_HOST_sdClk_0_INIT_DRIVESTATE 1u
#define SDIO_HOST_sdClk_0_INIT_MUXSEL 3u
#define SDIO_HOST_sdClk_0_INPUT_SYNC 2u
#define SDIO_HOST_sdClk_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define SDIO_HOST_sdClk_0_NUM 5u
#define SDIO_HOST_sdClk_0_PORT GPIO_PRT2
#define SDIO_HOST_sdClk_0_SLEWRATE CY_GPIO_SLEW_FAST
#define SDIO_HOST_sdClk_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define SDIO_HOST_sdClk_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define SDIO_HOST_sdClk_INBUF_ENABLED 0u
#define SDIO_HOST_sdClk_INIT_DRIVESTATE 1u
#define SDIO_HOST_sdClk_INIT_MUXSEL 3u
#define SDIO_HOST_sdClk_INPUT_SYNC 2u
#define SDIO_HOST_sdClk_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define SDIO_HOST_sdClk_NUM 5u
#define SDIO_HOST_sdClk_PORT GPIO_PRT2
#define SDIO_HOST_sdClk_SLEWRATE CY_GPIO_SLEW_FAST
#define SDIO_HOST_sdClk_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
